Repository mikepenz/MaterialDrawer, pull requests merged in 2020-10, with the labels that each got.

#2659 Fix v8.0.0 typos in MIGRATION.md
  MIGRATION.md
Labels: hacktoberfest-accepted

#2661 Automatic changelog generation for releases
  .github/config/configuration.json
  .github/workflows/ci.yml
Labels: other

#2662 Update dependencies (FastAdapter 5.2.4, Gradle Build Tools 4.1.0, ConstraintLayout 2.0.2)
  build.gradle
Labels: feature

#2668 Make enableProfileClick public again
  library/src/main/java/com/mikepenz/materialdrawer/widget/MiniDrawerSliderView.kt
Labels: feature

#2670 Fix MenuItem drawable being null causing problems
  library/src/main/java/com/mikepenz/materialdrawer/model/interfaces/Iconable.kt
Labels: fix
