Repository mikepenz/MaterialDrawer, pull requests merged in 2022-06, with the labels that each got.

#2780 Upgrade dependencies 2022.06.24
  app/build.gradle
  app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#2779 Enhance selected color selection MiniDrawerItem
  app/build.gradle
  materialdrawer/src/main/java/com/mikepenz/materialdrawer/model/MiniDrawerItem.kt
Labels: fix

#2782 Dependency Submission API
  .github/workflows/ci.yml
Labels: other

#2783 Update CI pipeline for dependency submission API
  .github/workflows/ci.yml
Labels: other

#2784 Run dependency submission action on dev branch
  .github/workflows/ci.yml
  .github/workflows/gradle-dependency-submission.yml
Labels: other
